### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by rvignolo** [frankdev7/rather-staking#1]
Hi @frankdev7, nice meeting you! I am a Principal Engineer at Rather Labs.

I just wanted highlight the following:

When a user either stakes or unstakes, the rewards should be updated for all users participating in the protocol. This is because the participation of each user changes when someone stakes or unstakes (the total staked amount changes, either decreases or diminishes). 

How would you consider that without making any loop in users? If I am not mistaken, you are not computing rewards correctly. 

You can think about a share price changing at each user interaction and consider that the amount of shares users have are constant (besides the amount hold by the account that performs the interaction).

**Comment by rvignolo** [comment]
Please make the repo private. Thanks!

**Comment by frankdev7** [comment]
> Hi @frankdev7, nice meeting you! I am a Principal Engineer at Rather Labs.
> 
> I just wanted highlight the following:
> 
> When a user either stakes or unstakes, the rewards should be updated for all users participating in the protocol. This is because the participation of each user changes when someone stakes or unstakes (the total staked amount changes, either decreases or diminishes).
> 
> How would you consider that without making any loop in users? If I am not mistaken, you are not computing rewards correctly.
> 
> You can think about a share price changing at each user interaction and consider that the amount of shares users have are constant (besides the amount hold by the account that performs the interaction).

Hi @rvignolo , nice meeting you too!

Yes, I am condisering changes in total staked amount to calculate the rewards here: 

`    #[view(getTotalStake)]
    fn total_stake(&self) -> BigUint {
        let total_stake = self.staked_addresses().iter().map(|address| {
            self.staking_position(&address).get()
        }).fold(BigUint::zero(), |acc, x| acc + x);
        total_stake
    }
`
However I am user a iterator to calculate the total staked (sum of individual stakes of each user), which is a kind of loop.

I like your idea aoubt share price: 
And should be implemente as: when a user stakes, they receive a certain number of shares equivalent to their stake. The rewards that each staker is entitled to is proportional to the number of shares they hold. The total number of shares and the total stake are updated every time a user stakes or unstakes, making sure the share price accurately reflects the current state of the pool.

Sure, there are improvements to do it in some cases that I am not considering:

- A user stakes at time t1 an amount of stake s1, after that same user stakes at time t2 and amount of stake s2 (the time period for each stake is currently not being considered).
- When an user fully unstakes, the rewards should be claimed automatically.
- When an user partially unstakes, the rewards for the amount of unstake u1 should be claimed automatically.

**Comment by rvignolo** [comment]
I see why you want to claim rewards automatically. Maybe you can avoid that by simply adding a storage that keeps track of those rewards.  

Finally, there is no need to have such a complicated `view` for `total_stake`. It is not a good idea if there are tons of users. You can just update such variable every time a user stakes or unstakes. It would be much more simpler

**Comment by frankdev7** [comment]
Hi @rvignolo, I have updated the "total stake" as a variable in storage 
`
    #[view(getTotalStake)]
    #[storage_mapper("totalStake")]
    fn total_stake(&self) -> SingleValueMapper<BigUint>;
`
and I'm using a struct to track all of a user's stakes.
`
#[derive(TypeAbi, TopEncode, TopDecode, PartialEq, Debug)]
pub struct StakingPosition<M: ManagedTypeApi> {
    pub stake_amount: BigUint<M>,
    pub start_timestamp: u64,
}
`

Each time a user stakes, it updates its value. Unstaking requires a bit more logic (because the straightforward method would be to iterate over that

`
    #[view(getStakingPositions)]
    #[storage_mapper("stakingPositions")]
    fn staking_positions(
        &self,
        addr: &ManagedAddress,
    ) -> VecMapper<StakingPosition<Self::Api>>;
`
